export const DEFAULT_REFUND_PERCENTAGE = 0.9;
export const MIN_REFUND_PERCENTAGE = 0;
export const MAX_REFUND_PERCENTAGE = 1;
export const DEFAULT_BOOKING_CAPACITY_MULTIPLIER = 1;
export const MIN_BOOKING_CAPACITY_MULTIPLIER = 1;
export const MAX_BOOKING_CAPACITY_MULTIPLIER = 10;
