begin;

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('tenant', 'landlord', 'admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'listing_type') then
    create type public.listing_type as enum ('long_term', 'short_stay');
  end if;

  if not exists (select 1 from pg_type where typname = 'house_type') then
    create type public.house_type as enum (
      'single_room',
      'bedsitter',
      'studio',
      'one_bedroom',
      'two_bedroom',
      'three_bedroom',
      'four_bedroom',
      'five_bedroom_plus',
      'maisonette',
      'townhouse',
      'bungalow',
      'villa',
      'apartment'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'booking_status') then
    create type public.booking_status as enum ('pending', 'reserved', 'expired', 'completed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typname = 'transaction_status') then
    create type public.transaction_status as enum ('pending', 'success', 'failed', 'refunded');
  end if;
end
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.enforce_listing_landlord_role()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.users u
    where u.id = new.landlord_id
      and u.role in ('landlord', 'admin')
  ) then
    raise exception 'listing.landlord_id must reference a user with landlord or admin role';
  end if;

  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  phone text unique,
  role public.user_role not null default 'tenant',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint users_full_name_not_blank check (char_length(btrim(full_name)) > 0),
  constraint users_phone_not_blank check (phone is null or char_length(btrim(phone)) > 0)
);

create table if not exists public.counties (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint counties_name_unique unique (name),
  constraint counties_name_not_blank check (char_length(btrim(name)) > 0)
);

create table if not exists public.towns (
  id bigint generated by default as identity primary key,
  county_id bigint not null references public.counties (id) on delete restrict,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint towns_county_name_unique unique (county_id, name),
  constraint towns_county_id_id_unique unique (county_id, id),
  constraint towns_name_not_blank check (char_length(btrim(name)) > 0)
);

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  town_id bigint not null references public.towns (id) on delete restrict,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint areas_town_name_unique unique (town_id, name),
  constraint areas_town_id_id_unique unique (town_id, id),
  constraint areas_name_not_blank check (char_length(btrim(name)) > 0)
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  price numeric(12, 2) not null,
  listing_type public.listing_type not null,
  house_type public.house_type not null,
  landlord_id uuid not null references public.users (id) on delete restrict,
  county_id bigint not null references public.counties (id) on delete restrict,
  town_id bigint not null references public.towns (id) on delete restrict,
  area_id bigint not null references public.areas (id) on delete restrict,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  maps_link text,
  is_verified boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint listings_title_not_blank check (char_length(btrim(title)) > 0),
  constraint listings_description_not_blank check (char_length(btrim(description)) > 0),
  constraint listings_price_non_negative check (price >= 0),
  constraint listings_maps_link_not_blank check (maps_link is null or char_length(btrim(maps_link)) > 0),
  constraint listings_latitude_range check (latitude is null or latitude between -90 and 90),
  constraint listings_longitude_range check (longitude is null or longitude between -180 and 180),
  constraint listings_coordinates_pair check (
    (latitude is null and longitude is null)
    or (latitude is not null and longitude is not null)
  ),
  constraint listings_county_town_consistency_fk
    foreign key (county_id, town_id)
    references public.towns (county_id, id)
    on delete restrict,
  constraint listings_town_area_consistency_fk
    foreign key (town_id, area_id)
    references public.areas (town_id, id)
    on delete restrict
);

create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings (id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint listing_images_image_url_not_blank check (char_length(btrim(image_url)) > 0),
  constraint listing_images_sort_order_non_negative check (sort_order >= 0),
  constraint listing_images_listing_url_unique unique (listing_id, image_url)
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete restrict,
  listing_id uuid not null references public.listings (id) on delete restrict,
  status public.booking_status not null default 'pending',
  deposit_amount numeric(12, 2) not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint bookings_deposit_amount_non_negative check (deposit_amount >= 0),
  constraint bookings_expiry_after_creation check (expires_at is null or expires_at > created_at),
  constraint bookings_active_status_requires_expiry check (
    status not in ('pending', 'reserved') or expires_at is not null
  )
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete restrict,
  booking_id uuid not null references public.bookings (id) on delete restrict,
  amount numeric(12, 2) not null,
  platform_fee numeric(12, 2) not null default 0,
  refund_amount numeric(12, 2) not null default 0,
  status public.transaction_status not null default 'pending',
  payment_provider text,
  provider_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint transactions_amount_non_negative check (amount >= 0),
  constraint transactions_platform_fee_non_negative check (platform_fee >= 0),
  constraint transactions_refund_amount_non_negative check (refund_amount >= 0),
  constraint transactions_platform_fee_lte_amount check (platform_fee <= amount),
  constraint transactions_refund_amount_lte_amount check (refund_amount <= amount),
  constraint transactions_payment_provider_not_blank check (
    payment_provider is null or char_length(btrim(payment_provider)) > 0
  ),
  constraint transactions_provider_reference_not_blank check (
    provider_reference is null or char_length(btrim(provider_reference)) > 0
  )
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.conversation_participants (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  last_read_at timestamptz,
  constraint conversation_participants_unique unique (conversation_id, user_id),
  constraint conversation_participants_last_read_after_join check (
    last_read_at is null or last_read_at >= created_at
  )
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_id uuid not null references public.users (id) on delete restrict,
  message_text text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint messages_message_text_not_blank check (char_length(btrim(message_text)) > 0),
  constraint messages_sender_is_participant_fk
    foreign key (conversation_id, sender_id)
    references public.conversation_participants (conversation_id, user_id)
    on delete restrict
);

create table if not exists public.saved_listings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  listing_id uuid not null references public.listings (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  constraint saved_listings_user_listing_unique unique (user_id, listing_id)
);

create table if not exists public.area_stats (
  id uuid primary key default gen_random_uuid(),
  area_id bigint not null references public.areas (id) on delete cascade,
  snapshot_date date not null default current_date,
  avg_price numeric(12, 2) not null default 0,
  listing_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint area_stats_avg_price_non_negative check (avg_price >= 0),
  constraint area_stats_listing_count_non_negative check (listing_count >= 0),
  constraint area_stats_area_snapshot_unique unique (area_id, snapshot_date)
);

create index if not exists idx_users_role on public.users (role);

create index if not exists idx_towns_county_id on public.towns (county_id);
create index if not exists idx_areas_town_id on public.areas (town_id);

create index if not exists idx_listings_area_price on public.listings (area_id, price);
create index if not exists idx_listings_landlord_id on public.listings (landlord_id);
create index if not exists idx_listings_location on public.listings (county_id, town_id, area_id);
create index if not exists idx_listings_type_house on public.listings (listing_type, house_type);
create index if not exists idx_listings_active_verified on public.listings (is_active, is_verified);

create index if not exists idx_listing_images_listing_id on public.listing_images (listing_id);

create index if not exists idx_bookings_listing_status on public.bookings (listing_id, status);
create index if not exists idx_bookings_user_status on public.bookings (user_id, status);
create index if not exists idx_bookings_expires_at on public.bookings (expires_at);

create unique index if not exists idx_bookings_one_active_entry_per_user_listing
  on public.bookings (user_id, listing_id)
  where status in ('pending', 'reserved');

create index if not exists idx_transactions_user_status on public.transactions (user_id, status);
create index if not exists idx_transactions_booking_id on public.transactions (booking_id);

create unique index if not exists idx_transactions_provider_reference
  on public.transactions (payment_provider, provider_reference)
  where provider_reference is not null;

create index if not exists idx_conversations_listing_id on public.conversations (listing_id);
create index if not exists idx_conversation_participants_user_id on public.conversation_participants (user_id);
create index if not exists idx_messages_conversation_created_at on public.messages (conversation_id, created_at);

create index if not exists idx_saved_listings_user_id on public.saved_listings (user_id);
create index if not exists idx_saved_listings_listing_id on public.saved_listings (listing_id);

create index if not exists idx_area_stats_area_snapshot on public.area_stats (area_id, snapshot_date desc);

drop trigger if exists trg_users_set_updated_at on public.users;
create trigger trg_users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists trg_counties_set_updated_at on public.counties;
create trigger trg_counties_set_updated_at
before update on public.counties
for each row
execute function public.set_updated_at();

drop trigger if exists trg_towns_set_updated_at on public.towns;
create trigger trg_towns_set_updated_at
before update on public.towns
for each row
execute function public.set_updated_at();

drop trigger if exists trg_areas_set_updated_at on public.areas;
create trigger trg_areas_set_updated_at
before update on public.areas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_listings_set_updated_at on public.listings;
create trigger trg_listings_set_updated_at
before update on public.listings
for each row
execute function public.set_updated_at();

drop trigger if exists trg_listing_images_set_updated_at on public.listing_images;
create trigger trg_listing_images_set_updated_at
before update on public.listing_images
for each row
execute function public.set_updated_at();

drop trigger if exists trg_bookings_set_updated_at on public.bookings;
create trigger trg_bookings_set_updated_at
before update on public.bookings
for each row
execute function public.set_updated_at();

drop trigger if exists trg_transactions_set_updated_at on public.transactions;
create trigger trg_transactions_set_updated_at
before update on public.transactions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_conversations_set_updated_at on public.conversations;
create trigger trg_conversations_set_updated_at
before update on public.conversations
for each row
execute function public.set_updated_at();

drop trigger if exists trg_area_stats_set_updated_at on public.area_stats;
create trigger trg_area_stats_set_updated_at
before update on public.area_stats
for each row
execute function public.set_updated_at();

drop trigger if exists trg_listings_enforce_landlord_role on public.listings;
create trigger trg_listings_enforce_landlord_role
before insert or update of landlord_id on public.listings
for each row
execute function public.enforce_listing_landlord_role();

commit;
